source $HOME/.zgen/zgen.zsh

if ! zgen saved; then

    # Load the oh-my-zsh's library.
    zgen oh-my-zsh

    # Bundles from the default repo (robbyrussell's oh-my-zsh).
    zgen oh-my-zsh plugins/git
    zgen oh-my-zsh plugins/archlinux
    zgen oh-my-zsh plugins/web-search
    zgen oh-my-zsh plugins/command-not-found

    # Load bundles from zsh-lovers.
    zgen load zsh-users/zsh-completions
    zgen load zsh-users/zsh-autosuggestions
    zgen load zsh-users/zsh-syntax-highlighting

    # Load the theme.
    zgen load denysdovhan/spaceship-prompt

    zgen save
fi